-- The whole schema, in one file.
--
-- docker-compose mounts this directory at /docker-entrypoint-initdb.d, and the
-- official Postgres image runs every .sql in it *once* — the first time the
-- data directory is empty. On every later `docker compose up` the volume
-- already holds a database, the entrypoint skips this file, and the rows you
-- created last time are still there. That skip is not a bug; it is exactly the
-- persistence this assignment is about.
--
-- Everything below is written to be safe to run twice anyway, so you can also
-- apply it by hand against an existing database:
--
--   docker compose exec -T db psql -U taskapi -d taskapi < db/init/001_schema.sql

CREATE TABLE IF NOT EXISTS tasks (
    -- GENERATED BY DEFAULT (not ALWAYS) so the seed rows below can claim ids
    -- 1, 2, 3 explicitly, while ordinary inserts still get their id from the
    -- sequence. The database hands out ids now; the application no longer
    -- computes max(id) + 1, and two clients inserting at the same moment can
    -- no longer be given the same id.
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The API rejects a blank title in the service layer. This CHECK says the
    -- same thing at the storage layer, so a blank title cannot get in through
    -- psql, a migration, or a second application later on.
    title TEXT    NOT NULL CHECK (btrim(title) <> ''),

    done  BOOLEAN NOT NULL DEFAULT FALSE
);

-- GET /tasks?done=... filters on this column, and /stats counts by it.
CREATE INDEX IF NOT EXISTS tasks_done_idx ON tasks (done);

-- The same three seed tasks the in-memory version started with, so a fresh
-- stack looks like the old one. Inserted only into an empty table: if you
-- already have rows, this is a no-op rather than a surprise duplicate.
INSERT INTO tasks (id, title, done)
SELECT seed.id, seed.title, seed.done
FROM (VALUES
    (1, 'Read the assignment', TRUE),
    (2, 'Build the API',       FALSE),
    (3, 'Write the README',    FALSE)
) AS seed (id, title, done)
WHERE NOT EXISTS (SELECT 1 FROM tasks);

-- Those explicit ids bypassed the identity sequence, which still thinks it is
-- about to hand out 1. Push it past the highest id in the table, or the very
-- first POST /tasks would fail on a duplicate primary key.
SELECT setval(
    pg_get_serial_sequence('tasks', 'id'),
    COALESCE((SELECT MAX(id) FROM tasks), 0) + 1,
    false
);
